# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Tripod' do
  
     
     # pod 'TripodPro', :path => '../TripodPro'
pod 'TripodPro',:git => "https://github.com/gettripod/ios-pro-framework.git", :tag => "0.0.1"


end
